### ISSUE TITLE
Error flashing

### ISSUE THREAD

**Issue by condor13** [TheKikGen/stm32-tkg-hid-bootloader#4]
Hello.
I`m having a little issue using the flasher. I flashed the bootloader using stlink successfully. Windows detects HID device, flasher detects hid device but gives "Error while sending firmware data to HID device." 
I have the bluepill pc13 board 64k flash. Do i have to make mods to the board like [here](https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Flashing-Bootloader-for-BluePill-Boards).
Thanks. 
Teodor.

**Comment by TheKikGen** [comment]
Hello,

What operating system are you using ?

Le mer. 12 août 2020 à 18:33, Teodor Nicolae <notifications@github.com> a
écrit :

**Comment by condor13** [comment]
Windows 7 x64 pro.

**Comment by condor13** [comment]
ok. your reply implied that i should try another os. so i used win10 pro. worked on first try. My norns loves this already :+1:
